name: commit build

on: [push]

jobs:
  build:

    runs-on: windows-latest
    strategy:
      matrix:
        dotnet-version: ['4.7.2' ]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Setup MSBuild 
        uses: microsoft/setup-msbuild@v1
        with:
          msbuild-architecture: x64
      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1
      - name: Go to github workspace
        run: cd $GITHUB_WORKSPACE
      - name: Go to client folder
        run: cd client
      - name: Install dependencies
        run: msbuild specify_client.csproj -t:restore
      - name: Build
        run: msbuild specify_client.csproj -property:Configuration=Release
      - name: Upload build
        uses: actions/upload-artifact@v3.1.2
        with:
          name: specify_client_commit
          path: bin\Release\specify_client.exe
