name: commit build

on: [push]

jobs:
  build:

    runs-on: windows-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Setup MSBuild 
        uses: microsoft/setup-msbuild@v1
        with:
          msbuild-architecture: x64
      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1
      - run: pwd
      - run: ls
      - name: Install dependencies
        run: msbuild client\client.sln -t:restore
      - name: Build
        run: msbuild client\client.sln -property:Configuration=Release
      - name: Upload build
        uses: actions/upload-artifact@v3.1.2
        with:
          name: specify_client_commit
          path: client\bin\Release\specify_client.exe
